id = "kadalas"
name = "Kadalas Theme"
version = "1.0.0"
schema_version = "0.2.0"
authors = ["Arjun K. <arjunkdot@gmail.com>"]
description = "A simple, easy on the eyes theme for Zed text editor."
repository = "https://github.com/arjunkdot/kadalas"
